### ISSUE TITLE
Middleware config per frontend

### ISSUE THREAD

**Issue by DorianGray** [timelinelabs/romulus#11]
Specifically for rewrites. There's no easy way to redirect http to https otherwise.

**Comment by lucmichalski** [comment]
+1

It would be great to create a middleware per frontend to access them, something equivalent to the vulcand requests to create a middleware:

eg: curl -X POST -H "Content-Type: application/json" \ http://PRIVATE_IP4:8182/v2/frontends/app1/middlewares\
     -d '{"Middleware": {
         "Id":"app1",
         "Priority":1,
         "Type":"rewrite",
         "Middleware":{
            "Regexp":"/api/app1/(.*)",
            "Replacement":"/$1",
            "RewriteBody":false,
            "Redirect":false}}}'

**Comment by albertrdixon** [comment]
Totally agree. Will add this similar to settings.

**Comment by alexkappa** [comment]
@albertrdixon I noticed this feature has landed in the dev branch, would this also work with custom middleware ([vbundle](http://vulcand.github.io/middlewares.html#vbundle))?
