### ISSUE TITLE
Support TLS

### ISSUE THREAD

**Issue by DorianGray** [timelinelabs/romulus#2]
http://www.vulcanproxy.com/proxy.html#tls-options

Having TLS support would be awesome

Maybe just allow manually setting things like listeners, hosts, and secrets from service files?

**Comment by albertrdixon** [comment]
Probably should not have auto closed this one.

`TLS` options set in `backendSettings` will be respected now.

I think `listeners`, `hosts`, and `secrets` are probably outside of the scope of romulus since they don't really map onto kubernetes elements.

**Comment by DorianGray** [comment]
Agreed, nice work =)

**Comment by cescoferraro** [comment]
@albertrdixon 
Is there any example of this implementation?
Does it require the `vulcand -sealKey="the-seal-key"`  flag?

something like?
`romulus/backend_settings: {"KeyPair": {"Cert": "base64-encoded-certificate", "Key": "base64-encoded-key-string"}}`
